#!/usr/bin/env bash

# This file is designed to set up a machine for development. Everything MUST be
# idempotent, meaning that rerunning this file should still result in the same
# state of the machine. Notable, it should be possible to run this on a
# partially set up machine and get to a working state.

# Make debugging things easier.
if [[ $1 == "--verbose" ]]; then
  set -x
fi
set -e


function brew_install_cask_if_not_installed() {
  local app_name="$1"
  local cask_name="$2"
  if ! mdfind -name "$app_name" | grep -q "$app_name"; then
    echo "Installing $app_name (via brew cask $cask_name)..."
    brew install --cask "$cask_name"
  fi
  echo "✅ $app_name"
}

DOTFILES_REPO_ROOT="$(dirname "$(dirname "$(realpath "$0")")")"

if grep -q docker /proc/1/cgroup 2> /dev/null; then
  echo "This is a Docker container!"
  echo

elif [[ "$OSTYPE" == "darwin"* ]]; then
  echo "This is a MacBook!"
  echo

  # Install Homebrew, if it is not installed.
  if ! which -s brew; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  echo "✅ Homebrew"

  for pkg in coreutils moreutils git pinentry-mac gnupg gh zplug asdf tree curl wget httpie hugo cloc; do
    if ! brew ls --version "$pkg" > /dev/null; then
      echo "Installing $pkg..."
      brew install "$pkg"
    fi
    echo "✅ $pkg"
  done

  brew_install_cask_if_not_installed "Scroll Reverser.app" "scroll-reverser"
  brew_install_cask_if_not_installed "Firefox.app" "firefox"
  brew_install_cask_if_not_installed "balenaEtcher.app" "balenaetcher"
  brew_install_cask_if_not_installed "Meld.app" "meld"
  brew_install_cask_if_not_installed "Visual Studio Code.app" "visual-studio-code"

  code \
    --install-extension ms-python.python \
    --install-extension ms-vscode.sublime-keybindings \
    --install-extension ms-vsliveshare.vsliveshare \
    --install-extension matklad.rust-analyzer \
    --install-extension sdras.night-owl
  echo "✅ Visual Studio Code extensions are installed!"

elif [[ "$(uname -s)" == "Linux" ]]; then
  echo "This is a Linux Machine!"
  echo




else
  echo -ne "\n\n\e[31mERROR: Not sure how to set up this machine!\e[0m\n\n"
  exit 1
fi

# Create Python virtual environment for running `scripts/setup`.
if [[ ! -d .venv ]]; then
  python3 -m venv .venv --upgrade
  .venv/bin/pip install wheel
  .venv/bin/pip install -r $DOTFILES_REPO_ROOT/requirements.txt
fi

# Create a ~/.dotfiles.toml, if it doesn't exist.
CONFIG_FILE=~/.dotfiles.toml
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "[repositories]\npersonal = \"$DOTFILES_REPO_ROOT\"" > $CONFIG_FILE
fi
